import { ENTRY_TYPES } from '../constants.js';

const CREATE_ENTRIES_TABLE = `
  CREATE TABLE IF NOT EXISTS ENTRIES
  (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    PATH TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    CATEGORY TEXT,
    CONTENT_TYPE TEXT,
    THUMBNAIL_PATH TEXT
  )
`;
const CREATE_ENTRIES_PATH_NAME_INDEX = `
  CREATE UNIQUE INDEX IF NOT EXISTS ENTRIES_PATH_NAME_INDEX
    ON ENTRIES (
      NAME,
      PATH
    )
`;
const CREATE_ENTRIES_PATH_ONLY_INDEX = `
  CREATE INDEX IF NOT EXISTS ENTRIES_PATH_INDEX
    ON ENTRIES (
      PATH
    )
`;

const CREATE_TAGS_TABLE = `
  CREATE TABLE IF NOT EXISTS TAGS
  (
    TAG TEXT NOT NULL,
    ENTRY_ID NUMBER NOT NULL,
    FOREIGN KEY(ENTRY_ID)
      REFERENCES ENTRIES (ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
  )
`;
const CREATE_TAG_NAME_INDEX = `
  CREATE INDEX IF NOT EXISTS TAG_NAME_INDEX
    ON TAGS (
      TAG
    )
`;
const CREATE_TAGS_ENTRY_ID_INDEX = `
  CREATE INDEX IF NOT EXISTS TAGS_ENTRY_ID_INDEX
    ON TAGS (
      ENTRY_ID
    )
`;
const CREATE_TAG_ENTRY_COMBO_INDEX = `
  CREATE UNIQUE INDEX IF NOT EXISTS TAG_NAME_INDEX
    ON TAGS (
      TAG
    )
`;

export const SETUP_QUERIES = [
  CREATE_ENTRIES_TABLE,
  CREATE_ENTRIES_PATH_NAME_INDEX,
  CREATE_ENTRIES_PATH_ONLY_INDEX,
  CREATE_TAGS_TABLE,
  CREATE_TAG_NAME_INDEX,
  CREATE_TAGS_ENTRY_ID_INDEX,
  CREATE_TAG_ENTRY_COMBO_INDEX,
];

export const INSERT_DIR_ENTRY_QUERY = `
  INSERT INTO ENTRIES (
    NAME,
    PATH,
    TYPE
  ) VALUES (
    ?,
    ?,
    '${ENTRY_TYPES.DIR}'
  )
`;

export const INSERT_FILE_ENTRY_QUERY = `
  INSERT INTO ENTRIES (
    NAME,
    PATH,
    TYPE,
    CATEGORY,
    CONTENT_TYPE
  ) VALUES (
    ?,
    ?,
    '${ENTRY_TYPES.FILE}',
    ?,
    ?
  )
`;

export const GET_ENTRIES_BY_PATH = `
  SELECT
    ID,
    NAME,
    PATH,
    TYPE,
    CATEGORY,
    CONTENT_TYPE
  FROM ENTRIES WHERE PATH=?
`;
